
-- 1. Criação das Tabelas

-- Tabela de Perfis (Vincula à tabela auth.users do Supabase)
create table public.profiles (
  id uuid not null references auth.users on delete cascade,
  role text not null default 'user', -- 'admin', 'owner', 'user'
  primary key (id)
);

-- Tabela de Configuração do Site (Aparência e Identidade)
create table public.site_config (
  id bigint generated by default as identity primary key,
  brand_name text default 'Minha Bicicletaria',
  brand_desc text default 'Descrição do negócio...',
  profile_image_url text default '',
  bg_color text default '#0056b3',
  bg_image text default '',
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Tabela de Links (Botões)
create table public.links (
  id bigint generated by default as identity primary key,
  label text not null,
  url text not null,
  icon_class text default 'fas fa-link',
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Habilitar Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.site_config enable row level security;
alter table public.links enable row level security;

-- 3. Políticas de Segurança (Policies)

-- PROFILES
-- Permitir leitura se o usuário for o dono do perfil ou se for admin
create policy "Public profiles are viewable by everyone" 
on public.profiles for select 
using ( true ); -- Simplificado para permitir checagem de role no login, mas idealmente seria restrito

-- SITE_CONFIG
-- Leitura pública (qualquer um vê o site)
create policy "Config is viewable by everyone" 
on public.site_config for select 
to anon, authenticated 
using ( true );

-- Edição apenas para admins
create policy "Admins can update config" 
on public.site_config for update 
to authenticated 
using ( 
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.role in ('admin', 'owner')
  )
);

-- LINKS
-- Leitura pública
create policy "Links are viewable by everyone" 
on public.links for select 
to anon, authenticated 
using ( true );

-- Edição completa para admins
create policy "Admins can insert links" 
on public.links for insert 
to authenticated 
with check (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.role in ('admin', 'owner')
  )
);

create policy "Admins can update links" 
on public.links for update 
to authenticated 
using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.role in ('admin', 'owner')
  )
);

create policy "Admins can delete links" 
on public.links for delete 
to authenticated 
using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.role in ('admin', 'owner')
  )
);

-- 4. Inserção de Dados Iniciais

-- Trigger para criar profile automaticamente ao criar usuário no Auth (Opcional, mas útil)
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, role)
  values (new.id, 'user'); -- Padrão é user, admin muda manualmente dps
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- Dados Iniciais para Configuração
insert into public.site_config (brand_name, brand_desc, bg_color)
values ('O Valdim Bicicletaria', 'Seu próximo pedal começa aqui.', '#0056b3');

-- Dados Iniciais para Links
insert into public.links (label, url, icon_class) values 
('CONTATO', 'https://wa.me/', 'fab fa-whatsapp'),
('LOCALIZAÇÃO', 'https://maps.google.com', 'fas fa-map-marker-alt'),
('CATÁLOGO', '#', 'fas fa-bicycle'),
('NOSSOS HORÁRIOS', '#', 'far fa-clock'),
('AVALIAÇÃO GOOGLE', '#', 'fab fa-google'),
('PERFIL INSTAGRAM', 'https://instagram.com', 'fab fa-instagram');

-- COMANDO PARA DAR PERMISSÃO DE ADMIN (Execute após criar seu usuário no painel do Supabase)
-- update public.profiles set role = 'admin' where id = 'ID_DO_SEU_USUARIO_NO_AUTH';
